In [2]:
x=5
y=10
print(x+y)

15


In [3]:
pip install numpy

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.4 MB 244.9 kB/s eta 0:00:49
   - -------------------------------------- 0.5/12.4 MB 244.9 kB/s eta 0:00:49
  


[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

In [ ]:
#one dimenstional array
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.shape

(3,)

In [ ]:
#two dimenstional array
arr2=np.array([[1,2],[3,4]])
print(arr2)

[[1 2]
 [3 4]]


In [11]:
arr2.shape

(2, 2)

In [ ]:
#three dimenstional array
arr3=np.array([[[1,2],[3,4]],
                [[5,6],[7,8]]])
print(arr3)
print(arr3.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [ ]:
#python list
py_list=[1,2,3]
print(py_list*2)

[1, 2, 3, 1, 2, 3]


In [16]:
print(py_list+[2])

[1, 2, 3, 2]


In [17]:
#Numpy list
np_array=np.array([1,2,3])
print(np_array*2)


[2 4 6]
